#!/bin/bash

minDedup=85
function cleanUp {
 rm -rf testDir test.index
}

function runVDOEstimator {
  sync
  ./vdoestimator --index test.index ./testDir
}

cleanUp
mkdir testDir
dd if=/dev/zero ibs=4k count=22 > testDir/data 2>/dev/null
dedupPercent=`runVDOEstimator | grep 'Dedupe Percentage' | awk '{print $3}' | sed 's/%//'`
dedupPercent=${dedupPercent/\.*}
if [ $dedupPercent -lt $minDedup ]; then
  echo Dedup too low: $dedupPercent
  exit 1  
else
  echo succeed: $dedupPercent
fi

dedup1=$dedupPercent

cleanUp
mkdir testDir
dd if=/dev/zero ibs=4k count=22 2>/dev/null | tr "\000" "\377" > testDir/data 
dedupPercent=`runVDOEstimator | grep 'Dedupe Percentage' | awk '{print $3}' | sed 's/%//'`
dedupPercent=${dedupPercent/\.*}
if [ $dedupPercent -lt $minDedup ]; then
  echo Dedup too low: $dedupPercent
  exit 1
else
  echo succeed: $dedupPercent
fi
dedup2=$dedupPercent

if [ $dedup1 != $dedup2 ]; then
  echo Dedup rate should be the same for the first two tests.
  exit 1;
fi
  
cleanUp
mkdir testDir
dd if=/dev/zero ibs=4k count=11 >  testDir/data 2>/dev/null
dd if=/dev/zero ibs=4k count=11 2>/dev/null | tr "\000" "\377" >> testDir/data 2>/dev/null
dedupPercent=`runVDOEstimator | grep 'Dedupe Percentage' | awk '{print $3}' | sed 's/%//'`
dedupPercent=${dedupPercent/\.*}
if [ $dedupPercent -lt $minDedup ]; then
  echo Dedup too low: $dedupPercent
  exit 1  
else
  echo succeed: $dedupPercent
fi

cleanUp
exit 0

